### ISSUE TITLE
Report an issue

### ISSUE THREAD

**Issue by brettmarquard** [jddamore/ccda-search#1]
To all pages, at bottom of page add a link from http://www.hl7.org/ccdasearch/index.html to this issues repo.

**Comment by LisaRNelson** [comment]
There are funky character in this constraint near the urn:hl7-org:sdtc: 

This patient MAY contain zero or more [0..*] sdtc:raceCode, which SHALL be selected from ValueSet Race Value Set  2.16.840.1.113883.1.11.14914 DYNAMIC (CONF:1198-7263).
Note: The sdtc:raceCode is only used to record additional values when the patient has indicated multiple races or additional race detail beyond the five categories required for Meaningful Use Stage 2. The prefix sdtc: SHALL be bound to the namespace ï¿½urn:hl7-org:sdtcï¿½. The use of the namespace provides a necessary extension to CDA R2 for the use of the additional raceCode elements.

**Comment by jddamore** [comment]
@brettmarquard This change should be able to go out with the October 2021 Errata update for C-CDA CG. Current work on this branch: https://github.com/jddamore/ccda-search/tree/CG-october-errata

**Comment by jddamore** [comment]
Note that I added this at bottom on all pages except the main page. It includes links to both JIRA and this repo's issues. Feedback welcome before final merge

**Comment by jddamore** [comment]
Merged. Fixed in current release.
