### ISSUE TITLE
Participant Clarification

### ISSUE THREAD

**Issue by dhit-mdavis** [jddamore/ccda-search#20]
Hi.

After reviewing the following 2 links, I'd like to confirm the following for clarity.

### 2 Links
Related Person Relationship and Name Participant
https://www.hl7.org/ccdasearch/templates/2.16.840.1.113883.10.20.22.5.8.html
https://www.hl7.org/ccdasearch/pdfs/2.16.840.1.113883.10.20.22.5.8.pdf

### Clarity
"This associatedEntity SHALL contain exactly one [1..1] @classCode="PRS" Person (_**CodeSystem: HL7RoleCode 2.16.840.1.113883.5.111**_) (CONF:4537-33076)."

When it says **CodeSystem: HL7RoleCode 2.16.840.1.113883.5.111** is it:
1. stating that the "PRS" code is a HL7RoleCode?
2. if it isn't stating that, what exactly is it stating?
3. if it is stating that the "PRS" code is a HL7RoleCode, isn't "PRS" a RoleClass vs RoleCode and if so, wouldn't it be tied to 2.16.840.1.113883.5.110 or am I misinterpreting?

RoleClass > https://build.fhir.org/ig/HL7/UTG/CodeSystem-v3-RoleClass.html
RoleCodes > https://build.fhir.org/ig/HL7/UTG/CodeSystem-v3-RoleCode.html

VSAC
RoleClasses > https://vsac.nlm.nih.gov/valueset/2.16.840.1.113883.11.20.9.33/expansion/Latest
![image](https://github.com/jddamore/ccda-search/assets/56314435/e7baacbb-8407-499d-a1ab-c6a3b3dca1bd)

RoleCodes > https://vsac.nlm.nih.gov/valueset/2.16.840.1.113883.11.20.12.1/expansion/Latest
![image](https://github.com/jddamore/ccda-search/assets/56314435/ef7be406-c65e-4a44-a0c0-853020999e79)

**Comment by jddamore** [comment]
@dhit-mdavis I think you're right about this observation but generally this is more of a standards question rather than an issue with this repo (issues for this repo are issues when the online tool doesn't match the published standard). 

Shoot me an email to johnd
at
moreinformatics.com 

And I'll try to broker a conversation with Gay. BTW, it appears that this PRS may be a problem elsewhere in C-CDA guide as well.

**Comment by dhit-mdavis** [comment]
Thanks for this clarity John.

Thanks for pointing out the following as well - I'll keep this in mind.
_"(issues for this repo are issues when the online tool doesn't match the published standard)"_

Sounds like I need to open another Jira ticket but I'll shoot this same info to your email @ johnd@moreinformatics.com first and wait for your guidance.

Appreciate your assistance here and the possible brokered convo with Gay.

_"BTW, it appears that this PRS may be a problem elsewhere in C-CDA guide as well."_
I'll keep this in mind as well

Thanks - Mat

**Comment by dhit-mdavis** [comment]
Email sent

**Comment by jddamore** [comment]
Closing this issue since a concern relateed to standard and not related to C-CDA online technical publication process.
