### ISSUE TITLE
Weird Characters in the note for sdtc:raceCode

### ISSUE THREAD

**Issue by LisaRNelson** [jddamore/ccda-search#3]
There are funky character in this constraint near the urn:hl7-org:sdtc:

This patient MAY contain zero or more [0..*] sdtc:raceCode, which SHALL be selected from ValueSet Race Value Set 2.16.840.1.113883.1.11.14914 DYNAMIC (CONF:1198-7263).
Note: The sdtc:raceCode is only used to record additional values when the patient has indicated multiple races or additional race detail beyond the five categories required for Meaningful Use Stage 2. The prefix sdtc: SHALL be bound to the namespace ï¿½urn:hl7-org:sdtcï¿½. The use of the namespace provides a necessary extension to CDA R2 for the use of the additional raceCode elements.

**Comment by jddamore** [comment]
@LisaRNelson  So I was able to isolate a bunch of the issues to a weird quote character from the import. I've gone ahead and fixed those in this commit: https://github.com/jddamore/ccda-search/commit/a97f7ef90d7f79ba8fd575d70b8943390dfc8015
this branch: https://github.com/jddamore/ccda-search/tree/CG-october-errata

**Comment by jddamore** [comment]
Merged. Fixed in current release.
