### ISSUE TITLE
Incorrect template name in the search response for Provenance - Author Participation

### ISSUE THREAD

**Issue by LisaRNelson** [jddamore/ccda-search#4]
The search results return Author Provenance which isn't a template name at all.  The search results should return the exact name of the template as it is defined in the Companion Guide.

**Comment by jddamore** [comment]
@LisaRNelson This should be able to go out in the October 2021 Errata fix for C-CDA CG. See branch: https://github.com/jddamore/ccda-search/tree/CG-october-errata

**Comment by jddamore** [comment]
Merged. Fixed in current release.
