### ISSUE TITLE
Clarification that Supplemental Templates are not included in navigation tool

### ISSUE THREAD

**Issue by GayDolin** [jddamore/ccda-search#5]
Current Text:
For the latest information on C-CDA, always refer to the HL7 C-CDA Page.

New Text:
For the latest information on C-CDA, or to access the Supplemental Implementation Guides, please refer to the HL7 C-CDA Page.

**Comment by jddamore** [comment]
@GayDolin This change should be able to go out with the October 2021 Errata update for C-CDA CG. Current work on this branch: https://github.com/jddamore/ccda-search/tree/CG-october-errata

**Comment by jddamore** [comment]
Merged. Fixed in current release.
