### ISSUE TITLE
Check that notes show up in line with conformance statements

### ISSUE THREAD

**Issue by jddamore** [jddamore/ccda-search#6]
For example: 
See between conformance 6 and 8. Some notes not nested in conformance are dropped
https://www.hl7.org/ccdasearch/templates/2.16.840.1.113883.10.20.22.4.16.html
https://www.hl7.org/ccdasearch/pdfs/2.16.840.1.113883.10.20.22.4.16.pdf

**Comment by jddamore** [comment]
It has been confirmed that notes below the conformance statements work but those that are above (often non-indented) are not coming through. Example template: 
https://www.hl7.org/ccdasearch/templates/2.16.840.1.113883.10.20.22.4.318.html
https://www.hl7.org/ccdasearch/pdfs/2.16.840.1.113883.10.20.22.4.318.pdf

**Comment by jddamore** [comment]
@GayDolin see above comments and example. Confirmed that is an issue. I will attempt to address in next automated refresh of content.

**Comment by GayDolin** [comment]
Thanks John!

**Comment by jlyle1** [comment]
I was about to leave this comment about immunization repeat number; looks like you're on it! Thanks!

**Comment by jddamore** [comment]
@jlyle1 I will try to address this in the next automated pull which I would estimate is Spring 2022 after ballot comments are completed on the Companion Guide with new templates (currently in Jan 2022 ballot cycle). That said, good to find another place I can check when I address.

**Comment by jddamore** [comment]
Resolved in https://github.com/jddamore/ccda-search/pull/9
